# Variables
@baseUrl = http://localhost:3000

###

# Health check
GET {{baseUrl}}/health

###
# Listar todos os clientes
GET {{baseUrl}}/api/clientes

###
# Contar clientes
GET {{baseUrl}}/api/clientes/contar

###
# Criar cliente
POST {{baseUrl}}/api/clientes
Content-Type: application/json

{
  "nome": "João Mineiro",
  "email": "maria123@gmail.com"
}

###
# Buscar por nome
GET {{baseUrl}}/api/clientes/nome/Jo

###
# Busca por id
GET {{baseUrl}}/api/clientes/1

###
# Atualizar cliente
PUT {{baseUrl}}/api/clientes/1
Content-Type: application/json

{
  "nome": "Maria Silva"
}

###
# Deletar
DELETE {{baseUrl}}/api/clientes/1