# Variables
@baseUrl = http://localhost:3000

###

# Health check
GET {{baseUrl}}/health

###
# Listar todos os clientes
GET {{baseUrl}}/api/clientes

###
# Contar clientes
GET {{baseUrl}}/api/clientes/contar

###
# Criar cliente
POST {{baseUrl}}/api/clientes
Content-Type: application/json

{
  "nome": "Arrascaeta",
  "email": "arrasca@gmail.com"
}

###
# Buscar por nome
GET {{baseUrl}}/api/clientes/nome/Ma

###
# Busca por id
GET {{baseUrl}}/api/clientes/4

###
# Atualizar cliente
PUT {{baseUrl}}/api/clientes/5
Content-Type: application/json

{
  "nome": "Pedro Afonso"
}

###
# Deletar
DELETE {{baseUrl}}/api/clientes/5